### ISSUE TITLE
Samples need to be updated

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#114]

**Comment by bhundven** [comment]
@stilor IIUC, all samples but the avr sample (PR #198) have been fixed and this enhancement should be closed soon?

**Comment by stilor** [comment]
I have all building except:
- i586-mingw32msvc,i686-none-linux-gnu (missing i586-mingw32msvc toolchain; that needs to be added to ct-ng?)
- nios2-elf-mingw32 (some mingw build error)
- powerpc-unknown-linux-uclibc (multiple problems; I have a partial fix that makes the build go up to libstdc++ build - but still does not fix it completely).

**Comment by bhundven** [comment]
As for powerpc-unknown-linux-uclibc, I am currently adding uClibc-ng, which should fix those issues.

**Comment by bhundven** [comment]
Anything mingw should be looked at by @mingwandroid or @diorcety.

**Comment by stilor** [comment]
That partial fix has a patch for building older MPFR (2.4.2) with newer 
host autotools; should I separate it and create a pull request for that?

**Comment by bhundven** [comment]
I would hold off on that for now.
