### ISSUE TITLE
GMP dependency failing to compile on Raspberry Pi 4

### ISSUE THREAD

**Issue by dmaroto21** [crosstool-ng/crosstool-ng#1248]
I am getting the following error when trying to install crosstool-ng. The idea is to use a Rpi4 to compile code for ESP32.

I have followed these instructions: https://docs.espressif.com/projects/esp-idf/en/release-v4.0/get-started/linux-setup-scratch.html

And I am getting the following error on build.log

[ALL  ]     armv7l-build_unknown-linux-gnueabihf-gcc -c -DHAVE_CONFIG_H -I. -I/home/pi/esp4/crosstool-NG/.build/xtensa-unknown-elf/src/gmp/mpn -I.. -D__GMP_WITHIN_GMP -I/home/pi/esp4/crosstool-NG/.build/xtensa-unknown-elf/src/gmp -DOPERATION_divrem_1 -O2 -g -pipe -I/home/pi/esp4/crosstool-NG/.build/xtensa-unknown-elf/buildtools/include -fexceptions -Wa,--noexecstack tmp-divrem_1.s -o divrem_1.o
[ALL  ]    tmp-divrem_1.s: Assembler messages:
[ALL  ]    tmp-divrem_1.s:129: Error: selected processor does not support `mls r1,r4,r8,r11' in ARM mode
[ALL  ]    tmp-divrem_1.s:145: Error: selected processor does not support `mls r1,r4,r8,r11' in ARM mode
[ALL  ]    tmp-divrem_1.s:158: Error: selected processor does not support `mls r1,r4,r8,r11' in ARM mode
[ALL  ]    tmp-divrem_1.s:175: Error: selected processor does not support `mls r1,r4,r3,r8' in ARM mode
[ALL  ]    tmp-divrem_1.s:209: Error: selected processor does not support `mls r11,r4,r12,r3' in ARM mode
[ERROR]    make[3]: *** [Makefile:768: divrem_1.lo] Error 1
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3642583/build.log)

Thank you for your help,

David

**Comment by cpackham** [comment]
Hi David,

Cc: @antmak 

Firstly https://github.com/espressif/crosstool-NG.git is a fork of crosstool-ng so you probably should be reporting issues there. But I see that they aren't setup for issues which is probably what brought you here. So let's see what we can do.

Looking at the build.log it looks like GMP has some assembly that the compiler on the RPi4 doesn't like. 

I happen to have a brand spanking new RPi4 at my disposal so I can try a few experiments on that. My build for the xtensa-fsf-elf sample config fails in a similar way.

Looks like a bug in GMP or we're not passing some required flags when building on an arm host might be worth hitting up https://gmplib.org/

Building on an x86_64 host seems to work fine.

**Comment by antmak** [comment]
Thanks for the reporting, guys. I suspect this is a common GMP and Raspbian collision, it's the same like https://brmlab.cz/user/jenda/rpi-gcc 

Probably, it solved in the current master branch of https://github.com/crosstool-ng/crosstool-ng (need to double check). We plan to rebase the ESP toolchain onto the latest ct-ng, but not in the nearest version, sorry.

@dmaroto21  If you just want to run esp32 compiler under RPi, try to use the official arm build of toolchain: https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp32-2019r1-linux-armel.tar.gz 

Also I bring apologies, will try to open the issues in the fork. At the moment please feel free to ask all esp specific questions in https://github.com/espressif/esp-idf/ 's issues

**Comment by cpackham** [comment]
@antmak it's not fixed in master but I'll take a look and see if I can figure it out. How big is the delta to upstream? Presumably it's actually in the gcc/binutils/newlib not ct-ng itself.

**Comment by cpackham** [comment]
Building GMP standalone on my RPi4 works. I think the problem is that ct-ng overrides CFLAGS which means the default -march=armv7-a -mfloat-abi=hard -mtune=cortex-a5 gets left out which leads the assembler to reject the code.

It should be possible to set some of the CFLAGS_FOR_HOST variables to handle this.

**Comment by dmaroto21** [comment]
First of all, thanks a lot for your help guys.

@cpackham You are right, the standalone GMP builds correctly on my Pi4 and the master branch still fails.

@antmak In the meantime, I will give the arm build a go and let you know.

**Comment by cpackham** [comment]
Setting `CT_EXTRA_CFLAGS_FOR_HOST="-march=armv7-a -mfloat-abi=hard -mtune=cortex-a5"` has got me past the GMP build error (the full build is still going).

**Comment by antmak** [comment]
@cpackham
> How big is the delta to upstream

Forked from https://github.com/crosstool-ng/crosstool-ng/commit/ab3c204aee88f08481f1f63825d0e94b082ef84e

Really thanks for your research!

@dmaroto21 Thank you for the feedback
